version: "3"
services:
  core:
    build: <path of Dockerfile>
    restart: always
    container_name: "core"
    ports:
      - "<host port>:8443" # When you use HTTPS
      - "<host port>:8080" # When you use HTTP
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - <local path>:<docker path>

  db:
    restart: always
    image: postgres
    container_name: "db"
    ports:
      - "<host port>:5432"
    networks:
          - backend
    environment:
      - PG_PASSWORD=core
      - DB_USER=core
      - DB_PASS=core
      - DB_NAME=core
    volumes:
      - <local path>:<docker path>

networks:
  back:
    driver: bridge